import type { LayerKind, ShaderParam, ShaderType } from "@/types";

// ─────────────────────────────────────────────────────────────────────────────
// Default shader parameter registry
// ─────────────────────────────────────────────────────────────────────────────

export function getDefaultParams(shaderType: ShaderType): ShaderParam[] {
  switch (shaderType) {
    case "pixelation":
      return [
        {
          key: "cellSize",
          label: "Cell Size",
          type: "float",
          value: 8,
          min: 4,
          max: 64,
          step: 1,
          group: "Grid",
          description: "Size of each pixel cell in screen pixels",
        },
        {
          key: "shape",
          label: "Shape",
          type: "enum",
          value: "square",
          options: [
            { label: "Square", value: "square" },
            { label: "Circle", value: "circle" },
            { label: "Diamond", value: "diamond" },
          ],
          group: "Grid",
          description: "Cell shape used to represent each pixel",
        },
        {
          key: "preserveAspect",
          label: "Preserve Aspect",
          type: "bool",
          value: true,
          group: "Grid",
          description: "Maintain square cells regardless of canvas aspect ratio",
        },
      ];

    case "halftone":
      return [
        {
          key: "dotSize",
          label: "Dot Size",
          type: "float",
          value: 8,
          min: 0,
          max: 20,
          step: 0.5,
          group: "Grid",
          description: "Luma-driven radius added on top of the minimum (bright → larger)",
        },
        {
          key: "dotMin",
          label: "Min Radius",
          type: "float",
          value: 2,
          min: 0,
          max: 10,
          step: 0.5,
          group: "Grid",
          description: "Minimum dot radius in pixels (keeps dots visible in dark areas)",
        },
        {
          key: "gridSpacing",
          label: "Grid Spacing",
          type: "float",
          value: 20,
          min: 4,
          max: 80,
          step: 1,
          group: "Grid",
          description: "Distance between dot centers in screen pixels",
        },
        {
          key: "shape",
          label: "Shape",
          type: "enum",
          value: "circle",
          options: [
            { label: "Circle", value: "circle" },
            { label: "Square", value: "square" },
            { label: "Diamond", value: "diamond" },
            { label: "Line", value: "line" },
          ],
          group: "Grid",
        },
        {
          key: "angle",
          label: "Angle",
          type: "float",
          value: 45,
          min: 0,
          max: 360,
          step: 1,
          group: "Grid",
          description: "Rotation angle of the halftone grid (degrees)",
        },
        {
          key: "colorMode",
          label: "Color Mode",
          type: "enum",
          value: "source",
          options: [
            { label: "Monochrome", value: "monochrome" },
            { label: "Source", value: "source" },
            { label: "Duotone", value: "duotone" },
          ],
          group: "Color",
        },
        {
          key: "duotoneLight",
          label: "Light Color",
          type: "color",
          value: "#F5F5F0",
          group: "Color",
          description: "Light tone color (used in duotone mode)",
        },
        {
          key: "duotoneDark",
          label: "Dark Color",
          type: "color",
          value: "#1d1d1c",
          group: "Color",
          description: "Dark tone color (used in duotone mode)",
        },
        {
          key: "contrast",
          label: "Contrast",
          type: "float",
          value: 1,
          min: 0,
          max: 2,
          step: 0.05,
          group: "Tone",
        },
        {
          key: "softness",
          label: "Softness",
          type: "float",
          value: 0.1,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Tone",
          description: "Anti-aliasing width at dot edges",
        },
        {
          key: "invertLuma",
          label: "Invert Luma",
          type: "bool",
          value: false,
          group: "Tone",
          description: "Invert luminance so dark areas produce large dots",
        },
        {
          key: "interactionInput",
          label: "Interaction",
          type: "enum",
          value: "none",
          options: [
            { label: "None", value: "none" },
            { label: "Fluid trail", value: "trail" },
            { label: "Displacement", value: "displacement" },
          ],
          group: "Interaction",
          description: "Use Interactivity layer textures to modulate dot size",
        },
        {
          key: "interactionAmount",
          label: "Amount",
          type: "float",
          value: 0.5,
          min: 0,
          max: 2,
          step: 0.01,
          group: "Interaction",
        },
      ];

    case "ascii":
      return [
        {
          key: "cellSize",
          label: "Cell Size",
          type: "float",
          value: 16,
          min: 4,
          max: 32,
          step: 1,
          group: "Grid",
        },
        {
          key: "charset",
          label: "Charset",
          type: "enum",
          value: "light",
          options: [
            { label: "Light  · .:-=+*#%@", value: "light" },
            { label: "Dense  · .',:;!|({#@", value: "dense" },
            { label: "Blocks · ░▒▓█", value: "blocks" },
            { label: "Hatch  · ╱╲╳░▒", value: "hatching" },
            { label: "Binary · 01", value: "binary" },
            { label: "Custom", value: "custom" },
          ],
          group: "Characters",
        },
        {
          key: "customChars",
          label: "Custom Chars",
          type: "enum",
          value: " .:-=+*#%@",
          group: "Characters",
          description: "Character sequence from light to dark (used when Charset = Custom)",
        },
        {
          key: "colorMode",
          label: "Color Mode",
          type: "enum",
          value: "monochrome",
          options: [
            { label: "Monochrome", value: "monochrome" },
            { label: "Source color", value: "source" },
            { label: "Green terminal", value: "green-terminal" },
          ],
          group: "Color",
        },
        {
          key: "bgOpacity",
          label: "BG Opacity",
          type: "float",
          value: 0,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Color",
        },
        {
          key: "fontWeight",
          label: "Font Weight",
          type: "enum",
          value: "regular",
          options: [
            { label: "Thin", value: "thin" },
            { label: "Regular", value: "regular" },
            { label: "Bold", value: "bold" },
          ],
          group: "Characters",
        },
        {
          key: "invert",
          label: "Invert",
          type: "bool",
          value: false,
          group: "Tone",
          description: "Swap light and dark character mapping",
        },
        {
          key: "interactionInput",
          label: "Interaction",
          type: "enum",
          value: "none",
          options: [
            { label: "None", value: "none" },
            { label: "Fluid trail", value: "trail" },
            { label: "Displacement", value: "displacement" },
          ],
          group: "Interaction",
          description: "Use Interactivity layer textures to modulate character density",
        },
        {
          key: "interactionAmount",
          label: "Amount",
          type: "float",
          value: 0.5,
          min: 0,
          max: 2,
          step: 0.01,
          group: "Interaction",
        },
        {
          key: "bloomEnabled",
          label: "Bloom",
          type: "bool",
          value: false,
          group: "Bloom",
          description: "Add glow around bright and saturated areas",
        },
        {
          key: "bloomThreshold",
          label: "Threshold",
          type: "float",
          value: 0.7,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Bloom",
          description: "Brightness above which pixels emit bloom (uses max channel, not luma)",
        },
        {
          key: "bloomSoftKnee",
          label: "Soft Knee",
          type: "float",
          value: 0.5,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Bloom",
          description: "Transition width around the threshold — higher = softer falloff",
        },
        {
          key: "bloomIntensity",
          label: "Intensity",
          type: "float",
          value: 1,
          min: 0,
          max: 3,
          step: 0.05,
          group: "Bloom",
        },
        {
          key: "bloomRadius",
          label: "Radius",
          type: "float",
          value: 5,
          min: 0,
          max: 20,
          step: 0.5,
          group: "Bloom",
          description: "Gaussian blur radius in pixels",
        },
        {
          key: "bloomBlendWithSource",
          label: "Blend With Source",
          type: "bool",
          value: true,
          group: "Bloom",
          description: "Add bloom on top of the ASCII output",
        },
      ];

    case "dithering":
      return [
        {
          key: "algorithm",
          label: "Algorithm",
          type: "enum",
          value: "ordered-bayer",
          options: [
            { label: "Ordered (Bayer)", value: "ordered-bayer" },
            { label: "Floyd-Steinberg", value: "floyd-steinberg" },
            { label: "Atkinson", value: "atkinson" },
            { label: "Blue Noise", value: "blue-noise" },
          ],
          group: "Method",
        },
        {
          key: "matrixSize",
          label: "Matrix Size",
          type: "enum",
          value: "4x4",
          options: [
            { label: "2×2", value: "2x2" },
            { label: "4×4", value: "4x4" },
            { label: "8×8", value: "8x8" },
          ],
          group: "Method",
          description: "Bayer matrix size — larger = finer dither pattern",
        },
        {
          key: "colorMode",
          label: "Color Mode",
          type: "enum",
          value: "monochrome",
          options: [
            { label: "Monochrome", value: "monochrome" },
            { label: "Source color", value: "source" },
            { label: "Custom palette", value: "palette" },
          ],
          group: "Color",
        },
        {
          key: "levels",
          label: "Levels",
          type: "int",
          value: 2,
          min: 2,
          max: 16,
          step: 1,
          group: "Tone",
          description: "Number of quantization levels before dithering",
        },
        {
          key: "spread",
          label: "Spread",
          type: "float",
          value: 1,
          min: 0,
          max: 2,
          step: 0.05,
          group: "Tone",
          description: "Dither intensity / error diffusion amount",
        },
        {
          key: "interactionInput",
          label: "Interaction",
          type: "enum",
          value: "none",
          options: [
            { label: "None", value: "none" },
            { label: "Fluid trail", value: "trail" },
            { label: "Displacement", value: "displacement" },
          ],
          group: "Interaction",
          description: "Use Interactivity layer textures to bias dither threshold",
        },
        {
          key: "interactionAmount",
          label: "Amount",
          type: "float",
          value: 0.5,
          min: 0,
          max: 2,
          step: 0.01,
          group: "Interaction",
        },
      ];

    case "bloom":
      return [
        {
          key: "threshold",
          label: "Threshold",
          type: "float",
          value: 0.7,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Extraction",
          description: "Luminance threshold above which pixels emit bloom",
        },
        {
          key: "softKnee",
          label: "Soft Knee",
          type: "float",
          value: 0.5,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Extraction",
          description: "Smooth the threshold transition to avoid hard clipping",
        },
        {
          key: "intensity",
          label: "Intensity",
          type: "float",
          value: 1,
          min: 0,
          max: 3,
          step: 0.05,
          group: "Bloom",
        },
        {
          key: "radius",
          label: "Radius",
          type: "float",
          value: 5,
          min: 0,
          max: 20,
          step: 0.5,
          group: "Bloom",
          description: "Blur kernel size in pixels",
        },
        {
          key: "blendWithSource",
          label: "Blend With Source",
          type: "bool",
          value: true,
          group: "Bloom",
          description: "Add bloom on top of the original image",
        },
      ];

    case "fluted-glass":
      return [
        {
          key: "flutes",
          label: "Flutes",
          type: "int",
          value: 20,
          min: 2,
          max: 100,
          step: 1,
          group: "Shape",
          description: "Number of ridges across the surface",
        },
        {
          key: "orientation",
          label: "Orientation",
          type: "enum",
          value: "vertical",
          options: [
            { label: "Vertical", value: "vertical" },
            { label: "Horizontal", value: "horizontal" },
            { label: "Radial", value: "radial" },
          ],
          group: "Shape",
        },
        {
          key: "distortionStrength",
          label: "Distortion",
          type: "float",
          value: 0.5,
          min: 0,
          max: 2,
          step: 0.05,
          group: "Optics",
        },
        {
          key: "refractionIndex",
          label: "Refraction Index",
          type: "float",
          value: 1.3,
          min: 1,
          max: 2,
          step: 0.01,
          group: "Optics",
        },
        {
          key: "tint",
          label: "Tint",
          type: "color",
          value: "rgba(0,0,0,0)",
          group: "Color",
        },
        {
          key: "blur",
          label: "Blur",
          type: "float",
          value: 0.5,
          min: 0,
          max: 5,
          step: 0.1,
          group: "Optics",
          description: "Directional blur along the flute axis",
        },
      ];

    case "progressive-blur":
      return [
        {
          key: "direction",
          label: "Direction",
          type: "enum",
          value: "top-to-bottom",
          options: [
            { label: "Top → Bottom", value: "top-to-bottom" },
            { label: "Bottom → Top", value: "bottom-to-top" },
            { label: "Left → Right", value: "left-to-right" },
            { label: "Right → Left", value: "right-to-left" },
            { label: "Center out", value: "center-out" },
            { label: "Radial", value: "radial" },
          ],
          group: "Shape",
        },
        {
          key: "startStrength",
          label: "Start Strength",
          type: "float",
          value: 0,
          min: 0,
          max: 20,
          step: 0.5,
          group: "Blur",
        },
        {
          key: "endStrength",
          label: "End Strength",
          type: "float",
          value: 8,
          min: 0,
          max: 20,
          step: 0.5,
          group: "Blur",
        },
        {
          key: "falloff",
          label: "Falloff",
          type: "enum",
          value: "ease-in-out",
          options: [
            { label: "Linear", value: "linear" },
            { label: "Ease in", value: "ease-in" },
            { label: "Ease out", value: "ease-out" },
            { label: "Ease in-out", value: "ease-in-out" },
          ],
          group: "Blur",
        },
        {
          key: "focusPoint",
          label: "Focus Point",
          type: "vec2",
          value: [0.5, 0.5],
          group: "Focus",
          description: "Normalized UV position of the sharp focus region",
        },
        {
          key: "focusSize",
          label: "Focus Size",
          type: "float",
          value: 0.3,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Focus",
        },
      ];

    case "warp-distortion":
      return [
        {
          key: "mode",
          label: "Mode",
          type: "enum",
          value: "wave",
          options: [
            { label: "Bulge", value: "bulge" },
            { label: "Wave", value: "wave" },
          ],
          group: "Distortion",
        },
        {
          key: "strength",
          label: "Strength",
          type: "float",
          value: 0.7,
          min: -2,
          max: 2,
          step: 0.01,
          group: "Distortion",
          description: "Main distortion amount (lens amount for bulge)",
        },
        {
          key: "radius",
          label: "Radius",
          type: "float",
          value: 0.35,
          min: 0.05,
          max: 1,
          step: 0.01,
          group: "Distortion",
          description: "Normalized influence radius around the center",
        },
        {
          key: "center",
          label: "Center",
          type: "vec2",
          value: [0.5, 0.5],
          group: "Distortion",
          description: "Normalized UV center of the effect",
        },
        {
          key: "waveAmplitude",
          label: "Wave Amplitude",
          type: "float",
          value: 0.015,
          min: 0,
          max: 0.08,
          step: 0.001,
          group: "Wave",
          description: "UV displacement magnitude for wave mode",
        },
        {
          key: "waveFrequency",
          label: "Wave Frequency",
          type: "float",
          value: 5,
          min: 0.5,
          max: 20,
          step: 0.1,
          group: "Wave",
          description: "Number of ripple bands within the radius",
        },
        {
          key: "waveSpeed",
          label: "Wave Speed",
          type: "float",
          value: 1,
          min: -6,
          max: 6,
          step: 0.05,
          group: "Wave",
          description: "Animation speed for wave mode (0 = static)",
        },
        {
          key: "interactionInput",
          label: "Interaction Input",
          type: "enum",
          value: "none",
          options: [
            { label: "None", value: "none" },
            { label: "Displacement", value: "displacement" },
            { label: "Trail", value: "trail" },
          ],
          group: "Interaction",
          description: "Drive distortion using the Interactivity layer texture",
        },
        {
          key: "interactionAmount",
          label: "Interaction Amount",
          type: "float",
          value: 0,
          min: 0,
          max: 1.5,
          step: 0.01,
          group: "Interaction",
          description: "How strongly interactivity textures warp the UVs",
        },
      ];

    case "chromatic-aberration":
      return [
        {
          key: "mode",
          label: "Mode",
          type: "enum",
          value: "radial",
          options: [
            { label: "Radial", value: "radial" },
            { label: "Directional", value: "directional" },
          ],
          group: "Prism",
          description: "Radial adds edge fringing; directional applies a global split axis",
        },
        {
          key: "amount",
          label: "Amount",
          type: "float",
          value: 6,
          min: 0,
          max: 24,
          step: 0.1,
          group: "Prism",
          description: "RGB separation strength in screen pixels",
        },
        {
          key: "angle",
          label: "Angle",
          type: "float",
          value: 0,
          min: 0,
          max: 360,
          step: 1,
          group: "Prism",
          description: "Split direction when mode = directional",
        },
        {
          key: "center",
          label: "Center",
          type: "vec2",
          value: [0.5, 0.5],
          group: "Prism",
          description: "UV origin for radial fringing",
        },
        {
          key: "falloff",
          label: "Falloff",
          type: "float",
          value: 1.2,
          min: 0.1,
          max: 4,
          step: 0.05,
          group: "Prism",
          description: "How fast radial split ramps toward the edges",
        },
        {
          key: "spectrum",
          label: "Spectrum",
          type: "enum",
          value: "natural",
          options: [
            { label: "Natural", value: "natural" },
            { label: "CMY", value: "cmy" },
            { label: "Neon", value: "neon" },
          ],
          group: "Color",
          description: "Color channel separation style",
        },
        {
          key: "blend",
          label: "Blend",
          type: "float",
          value: 0.85,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Color",
          description: "Mix between clean source and prism-split output",
        },
      ];

    case "noise-generator":
      return [
        {
          key: "algorithm",
          label: "Algorithm",
          type: "enum",
          value: "perlin",
          options: [
            { label: "Perlin", value: "perlin" },
            { label: "Simplex", value: "simplex" },
            { label: "Voronoi", value: "voronoi" },
          ],
          group: "Noise",
        },
        {
          key: "scale",
          label: "Scale",
          type: "float",
          value: 8,
          min: 1,
          max: 64,
          step: 0.1,
          group: "Noise",
          description: "Frequency of the procedural pattern",
        },
        {
          key: "intensity",
          label: "Intensity",
          type: "float",
          value: 1,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Tone",
          description: "Blend amount between source and generated noise",
        },
        {
          key: "contrast",
          label: "Contrast",
          type: "float",
          value: 1,
          min: 0,
          max: 2.5,
          step: 0.01,
          group: "Tone",
          description: "Noise contrast around mid-gray",
        },
        {
          key: "invert",
          label: "Invert",
          type: "bool",
          value: false,
          group: "Tone",
        },
        {
          key: "speed",
          label: "Speed",
          type: "float",
          value: 0.35,
          min: -6,
          max: 6,
          step: 0.05,
          group: "Animation",
          description: "Animation speed (0 = static)",
        },
      ];

    case "mesh-gradient":
      return [
        {
          key: "point1",
          label: "Point 1",
          type: "vec2",
          value: [0.18, 0.2],
          group: "Control Points",
        },
        {
          key: "color1",
          label: "Color 1",
          type: "color",
          value: "#ff6a1f",
          group: "Control Points",
        },
        {
          key: "point2",
          label: "Point 2",
          type: "vec2",
          value: [0.82, 0.22],
          group: "Control Points",
        },
        {
          key: "color2",
          label: "Color 2",
          type: "color",
          value: "#ff3d81",
          group: "Control Points",
        },
        {
          key: "point3",
          label: "Point 3",
          type: "vec2",
          value: [0.25, 0.82],
          group: "Control Points",
        },
        {
          key: "color3",
          label: "Color 3",
          type: "color",
          value: "#3b82f6",
          group: "Control Points",
        },
        {
          key: "point4",
          label: "Point 4",
          type: "vec2",
          value: [0.8, 0.78],
          group: "Control Points",
        },
        {
          key: "color4",
          label: "Color 4",
          type: "color",
          value: "#ffd166",
          group: "Control Points",
        },
        {
          key: "falloff",
          label: "Falloff",
          type: "float",
          value: 2.4,
          min: 0.2,
          max: 6,
          step: 0.01,
          group: "Gradient",
          description: "How quickly each control point influence fades",
        },
        {
          key: "intensity",
          label: "Intensity",
          type: "float",
          value: 1,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Gradient",
          description: "Blend amount between source and gradient color",
        },
        {
          key: "animate",
          label: "Animate",
          type: "bool",
          value: false,
          group: "Animation",
        },
        {
          key: "speed",
          label: "Speed",
          type: "float",
          value: 0.35,
          min: -3,
          max: 3,
          step: 0.01,
          group: "Animation",
          description: "Animation speed for drifting control points",
        },
        {
          key: "drift",
          label: "Drift",
          type: "float",
          value: 0.06,
          min: 0,
          max: 0.2,
          step: 0.005,
          group: "Animation",
          description: "How far control points drift from their base positions",
        },
      ];

    case "guilloche":
      return [
        {
          key: "pattern",
          label: "Pattern",
          type: "enum",
          value: "rosette",
          options: [
            { label: "Rosette", value: "rosette" },
            { label: "Weave", value: "weave" },
            { label: "Radial Lace", value: "radial-lace" },
          ],
          group: "Pattern",
        },
        {
          key: "frequency1",
          label: "Frequency 1",
          type: "float",
          value: 7,
          min: 0.5,
          max: 40,
          step: 0.1,
          group: "Pattern",
        },
        {
          key: "frequency2",
          label: "Frequency 2",
          type: "float",
          value: 17,
          min: 0.5,
          max: 80,
          step: 0.1,
          group: "Pattern",
        },
        {
          key: "phase",
          label: "Phase",
          type: "float",
          value: 0,
          min: -12,
          max: 12,
          step: 0.01,
          group: "Pattern",
        },
        {
          key: "warp",
          label: "Warp",
          type: "float",
          value: 0.8,
          min: 0,
          max: 4,
          step: 0.01,
          group: "Pattern",
        },
        {
          key: "lineWidth",
          label: "Line Width",
          type: "float",
          value: 0.12,
          min: 0.005,
          max: 0.5,
          step: 0.001,
          group: "Lines",
        },
        {
          key: "softness",
          label: "Softness",
          type: "float",
          value: 0.05,
          min: 0.001,
          max: 0.25,
          step: 0.001,
          group: "Lines",
        },
        {
          key: "foreground",
          label: "Foreground",
          type: "color",
          value: "#121212",
          group: "Color",
        },
        {
          key: "background",
          label: "Background",
          type: "color",
          value: "#f7f1e8",
          group: "Color",
        },
        {
          key: "intensity",
          label: "Intensity",
          type: "float",
          value: 0.9,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Color",
          description: "Blend amount between source and guilloche pattern",
        },
        {
          key: "animate",
          label: "Animate",
          type: "bool",
          value: false,
          group: "Animation",
        },
        {
          key: "speed",
          label: "Speed",
          type: "float",
          value: 0.2,
          min: -4,
          max: 4,
          step: 0.01,
          group: "Animation",
        },
      ];

    case "sdf-shapes":
      return [
        {
          key: "mode",
          label: "Mode",
          type: "enum",
          value: "2d",
          options: [
            { label: "2D", value: "2d" },
            { label: "3D", value: "3d" },
          ],
          group: "Shape",
        },
        {
          key: "shape2d",
          label: "2D Primitive",
          type: "enum",
          value: "circle",
          options: [
            { label: "Circle", value: "circle" },
            { label: "Box", value: "box" },
            { label: "Rounded Box", value: "rounded-box" },
            { label: "Ring", value: "ring" },
          ],
          group: "Shape",
        },
        {
          key: "shape3d",
          label: "3D Primitive",
          type: "enum",
          value: "sphere",
          options: [
            { label: "Sphere", value: "sphere" },
            { label: "Box", value: "box" },
            { label: "Torus", value: "torus" },
          ],
          group: "Shape",
        },
        {
          key: "center",
          label: "Center",
          type: "vec2",
          value: [0.5, 0.5],
          group: "Transform",
        },
        {
          key: "size2d",
          label: "Size 2D",
          type: "vec2",
          value: [0.28, 0.22],
          group: "Transform",
        },
        {
          key: "sizeZ",
          label: "Depth",
          type: "float",
          value: 0.24,
          min: 0.05,
          max: 1.0,
          step: 0.01,
          group: "Transform",
        },
        {
          key: "radius",
          label: "Radius",
          type: "float",
          value: 0.32,
          min: 0.05,
          max: 1.2,
          step: 0.01,
          group: "Shape",
        },
        {
          key: "thickness",
          label: "Thickness",
          type: "float",
          value: 0.08,
          min: 0.01,
          max: 0.6,
          step: 0.01,
          group: "Shape",
          description: "Ring/torus tube thickness",
        },
        {
          key: "roundness",
          label: "Roundness",
          type: "float",
          value: 0.06,
          min: 0,
          max: 0.4,
          step: 0.005,
          group: "Shape",
        },
        {
          key: "rotation",
          label: "Rotation",
          type: "float",
          value: 0,
          min: -6.283,
          max: 6.283,
          step: 0.01,
          group: "Transform",
        },
        {
          key: "softness",
          label: "Softness",
          type: "float",
          value: 0.03,
          min: 0.001,
          max: 0.2,
          step: 0.001,
          group: "Appearance",
        },
        {
          key: "color",
          label: "Color",
          type: "color",
          value: "#ff6a1f",
          group: "Appearance",
        },
        {
          key: "background",
          label: "Background",
          type: "color",
          value: "#0d0f10",
          group: "Appearance",
        },
        {
          key: "invert",
          label: "Invert",
          type: "bool",
          value: false,
          group: "Appearance",
        },
        {
          key: "intensity",
          label: "Intensity",
          type: "float",
          value: 0.9,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Appearance",
        },
        {
          key: "animate",
          label: "Animate",
          type: "bool",
          value: false,
          group: "Animation",
        },
        {
          key: "speed",
          label: "Speed",
          type: "float",
          value: 0.45,
          min: -4,
          max: 4,
          step: 0.01,
          group: "Animation",
        },
      ];

    case "3d-shapes":
      return [
        {
          key: "shape",
          label: "Shape",
          type: "enum",
          value: "sphere",
          options: [
            { label: "Sphere", value: "sphere" },
            { label: "Cube", value: "cube" },
            { label: "Torus", value: "torus" },
            { label: "Prism", value: "prism" },
          ],
          group: "Shape",
        },
        {
          key: "material",
          label: "Material",
          type: "enum",
          value: "matte",
          options: [
            { label: "Matte", value: "matte" },
            { label: "Metal", value: "metal" },
            { label: "Neon", value: "neon" },
            { label: "Clay", value: "clay" },
          ],
          group: "Material",
        },
        {
          key: "size",
          label: "Size",
          type: "vec3",
          value: [0.36, 0.28, 0.24],
          group: "Shape",
          description: "XYZ size for box/prism forms",
        },
        {
          key: "radius",
          label: "Radius",
          type: "float",
          value: 0.38,
          min: 0.05,
          max: 1.2,
          step: 0.01,
          group: "Shape",
        },
        {
          key: "thickness",
          label: "Thickness",
          type: "float",
          value: 0.1,
          min: 0.01,
          max: 0.6,
          step: 0.01,
          group: "Shape",
          description: "Torus/prism thickness control",
        },
        {
          key: "roundness",
          label: "Roundness",
          type: "float",
          value: 0.05,
          min: 0,
          max: 0.3,
          step: 0.005,
          group: "Shape",
        },
        {
          key: "rotation",
          label: "Rotation",
          type: "float",
          value: 0,
          min: -6.283,
          max: 6.283,
          step: 0.01,
          group: "Transform",
        },
        {
          key: "ambient",
          label: "Ambient",
          type: "float",
          value: 0.18,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Material",
        },
        {
          key: "color",
          label: "Color",
          type: "color",
          value: "#ff6a1f",
          group: "Material",
        },
        {
          key: "background",
          label: "Background",
          type: "color",
          value: "#0b0e10",
          group: "Material",
        },
        {
          key: "environment",
          label: "Environment",
          type: "enum",
          value: "studio",
          options: [
            { label: "Studio", value: "studio" },
            { label: "Apartment", value: "apartment" },
            { label: "City", value: "city" },
            { label: "Dawn", value: "dawn" },
            { label: "Sunset", value: "sunset" },
            { label: "Forest", value: "forest" },
            { label: "Lobby", value: "lobby" },
            { label: "Night", value: "night" },
            { label: "Park", value: "park" },
            { label: "Warehouse", value: "warehouse" },
            { label: "Custom", value: "custom" },
          ],
          group: "Environment",
        },
        {
          key: "environmentStrength",
          label: "Env Strength",
          type: "float",
          value: 1,
          min: 0,
          max: 2,
          step: 0.01,
          group: "Environment",
        },
        {
          key: "showEnvironmentBackground",
          label: "Show HDRI BG",
          type: "bool",
          value: true,
          group: "Environment",
        },
        {
          key: "environmentBlur",
          label: "BG Blur",
          type: "float",
          value: 0,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Environment",
          description: "Blur amount for HDRI background",
        },
        {
          key: "environmentBackgroundIntensity",
          label: "BG Intensity",
          type: "float",
          value: 1,
          min: 0,
          max: 3,
          step: 0.01,
          group: "Environment",
          description: "Brightness of visible HDRI background",
        },
        {
          key: "cameraYaw",
          label: "Camera Yaw",
          type: "float",
          value: 0,
          min: -6.283,
          max: 6.283,
          step: 0.01,
          group: "Camera",
        },
        {
          key: "cameraPitch",
          label: "Camera Pitch",
          type: "float",
          value: 0.15,
          min: -1.2,
          max: 1.2,
          step: 0.01,
          group: "Camera",
        },
        {
          key: "cameraDistance",
          label: "Camera Distance",
          type: "float",
          value: 2.8,
          min: 0.5,
          max: 8,
          step: 0.01,
          group: "Camera",
        },
        {
          key: "autoOrbit",
          label: "Auto Orbit",
          type: "bool",
          value: false,
          group: "Camera",
        },
        {
          key: "orbitSpeed",
          label: "Orbit Speed",
          type: "float",
          value: 0.3,
          min: -3,
          max: 3,
          step: 0.01,
          group: "Camera",
        },
        {
          key: "animation",
          label: "Animation",
          type: "enum",
          value: "none",
          options: [
            { label: "None", value: "none" },
            { label: "Rotate", value: "rotate" },
            { label: "Float", value: "float" },
            { label: "Rotate + Float", value: "rotate-float" },
          ],
          group: "Animation",
        },
        {
          key: "speed",
          label: "Speed",
          type: "float",
          value: 0.55,
          min: -4,
          max: 4,
          step: 0.01,
          group: "Animation",
        },
        {
          key: "intensity",
          label: "Intensity",
          type: "float",
          value: 0.9,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Material",
        },
      ];

    case "grain":
      return [
        {
          key: "intensity",
          label: "Intensity",
          type: "float",
          value: 0.15,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Grain",
        },
        {
          key: "size",
          label: "Size",
          type: "float",
          value: 1,
          min: 0.5,
          max: 3,
          step: 0.1,
          group: "Grain",
          description: "Scale of the noise pattern",
        },
        {
          key: "speed",
          label: "Speed",
          type: "float",
          value: 1,
          min: 0,
          max: 2,
          step: 0.05,
          group: "Animation",
          description: "Animation rate (0 = static grain)",
        },
        {
          key: "monochrome",
          label: "Monochrome",
          type: "bool",
          value: true,
          group: "Grain",
          description: "Single-channel luminance noise vs. per-channel RGB noise",
        },
        {
          key: "blendMode",
          label: "Blend Mode",
          type: "enum",
          value: "overlay",
          options: [
            { label: "Overlay", value: "overlay" },
            { label: "Soft Light", value: "soft-light" },
            { label: "Add", value: "add" },
          ],
          group: "Grain",
        },
      ];

    case "interactivity":
      return [
        {
          key: "effect",
          label: "Effect",
          type: "enum",
          value: "trail",
          options: [
            { label: "Trail", value: "trail" },
            { label: "Repel", value: "repel" },
            { label: "Attract", value: "attract" },
          ],
          group: "Effect",
        },
        {
          key: "radius",
          label: "Radius",
          type: "float",
          value: 50,
          min: 10,
          max: 200,
          step: 1,
          group: "Effect",
          description: "Interaction radius in screen pixels",
        },
        {
          key: "strength",
          label: "Strength",
          type: "float",
          value: 0.5,
          min: 0,
          max: 2,
          step: 0.05,
          group: "Effect",
        },
        {
          key: "decay",
          label: "Decay",
          type: "float",
          value: 0.95,
          min: 0,
          max: 1,
          step: 0.01,
          group: "Effect",
          description: "How quickly the effect fades each frame",
        },
        {
          key: "color",
          label: "Color",
          type: "color",
          value: "#ff6a1f",
          group: "Appearance",
        },
        {
          key: "trailLength",
          label: "Trail Length",
          type: "int",
          value: 20,
          min: 5,
          max: 50,
          step: 1,
          group: "Effect",
          description: "Number of stored positions in the trail buffer",
        },
        {
          key: "trailRouting",
          label: "Trail Routing",
          type: "enum",
          value: "add",
          options: [
            { label: "Add over source", value: "add" },
            { label: "Trail only", value: "source" },
            { label: "Use as mask", value: "mask" },
            { label: "Use as displacement", value: "displace" },
          ],
          group: "Trail Routing",
          description: "How the fluid trail is routed into this layer output",
        },
        {
          key: "trailDisplaceAmount",
          label: "Displace Amount",
          type: "float",
          value: 0.0035,
          min: 0,
          max: 0.03,
          step: 0.0005,
          group: "Trail Routing",
          description: "UV displacement scale when routing mode is displacement",
        },
        {
          key: "curlStrength",
          label: "Curl Strength",
          type: "float",
          value: 256,
          min: 0,
          max: 512,
          step: 1,
          group: "Fluid",
          description: "Vorticity force applied to the velocity field",
        },
        {
          key: "pressureIterations",
          label: "Pressure Iterations",
          type: "int",
          value: 12,
          min: 1,
          max: 30,
          step: 1,
          group: "Fluid",
          description: "Jacobi solver iterations for incompressibility",
        },
        {
          key: "fluidRadius",
          label: "Fluid Radius",
          type: "float",
          value: 2.45,
          min: 0.2,
          max: 6,
          step: 0.01,
          group: "Fluid",
          description: "Simulation splat radius used by the fluid solver",
        },
        {
          key: "densityDissipation",
          label: "Density Dissipation",
          type: "float",
          value: 0.96,
          min: 0.5,
          max: 1,
          step: 0.001,
          group: "Fluid",
        },
        {
          key: "velocityDissipation",
          label: "Velocity Dissipation",
          type: "float",
          value: 0.8,
          min: 0.5,
          max: 1,
          step: 0.001,
          group: "Fluid",
        },
        {
          key: "pressureDissipation",
          label: "Pressure Dissipation",
          type: "float",
          value: 0.92,
          min: 0.5,
          max: 1,
          step: 0.001,
          group: "Fluid",
        },
      ];

    case "masonry":
      return [
        {
          key: "columns",
          label: "Columns",
          type: "int",
          value: 4,
          min: 2,
          max: 16,
          step: 1,
          group: "Grid",
          description: "Horizontal cell count",
        },
        {
          key: "rows",
          label: "Rows",
          type: "int",
          value: 4,
          min: 2,
          max: 16,
          step: 1,
          group: "Grid",
          description: "Vertical cell count",
        },
        {
          key: "animationMode",
          label: "Animation Mode",
          type: "enum",
          value: "adaptive",
          options: [
            { label: "Adaptive", value: "adaptive" },
            { label: "Always", value: "always" },
            { label: "Hover + Move", value: "hover-move" },
            { label: "Off", value: "off" },
          ],
          group: "Animation",
          description: "Adaptive = video auto / image hover+move",
        },
        {
          key: "cursorPush",
          label: "Cursor Push",
          type: "float",
          value: 8,
          min: 0,
          max: 24,
          step: 0.25,
          group: "Animation",
          description: "How strongly tiles drift in cursor direction",
        },
        {
          key: "interval",
          label: "Interval",
          type: "float",
          value: 1.0,
          min: 0,
          max: 10,
          step: 0.1,
          group: "Animation",
          description: "Seconds between reshuffles; 0 = off",
        },
        {
          key: "animDuration",
          label: "Slide Duration",
          type: "float",
          value: 0.4,
          min: 0,
          max: 1.5,
          step: 0.05,
          group: "Animation",
          description: "Slide animation duration in seconds; 0 = instant snap",
        },
      ];

    default:
      return [];
  }
}

/** Human-readable default name for a layer given its shader type */
export function getDefaultLayerName(
  shaderType: ShaderType,
  existingCount: number,
): string {
  const names: Record<ShaderType, string> = {
    pixelation: "Pixelation",
    halftone: "Halftone",
    ascii: "ASCII",
    dithering: "Dithering",
    bloom: "Bloom",
    "fluted-glass": "Fluted Glass",
    "progressive-blur": "Progressive Blur",
    "warp-distortion": "Warp Distortion",
    "chromatic-aberration": "Prism Split",
    "noise-generator": "Noise Generator",
    "mesh-gradient": "Mesh Gradient",
    guilloche: "Guilloche",
    "sdf-shapes": "SDF Shapes",
    "3d-shapes": "3D Shapes",
    grain: "Grain",
    interactivity: "Interactivity",
    masonry: "Masonry",
  };
  const base = names[shaderType] ?? "Layer";
  return existingCount > 0 ? `${base} ${existingCount + 1}` : base;
}

export function getDefaultModelParams(): ShaderParam[] {
  return [
    {
      key: "environment",
      label: "Environment",
      type: "enum",
      value: "studio",
      options: [
        { label: "Studio", value: "studio" },
        { label: "Apartment", value: "apartment" },
        { label: "City", value: "city" },
        { label: "Dawn", value: "dawn" },
        { label: "Sunset", value: "sunset" },
        { label: "Forest", value: "forest" },
        { label: "Lobby", value: "lobby" },
        { label: "Night", value: "night" },
        { label: "Park", value: "park" },
        { label: "Warehouse", value: "warehouse" },
        { label: "Custom", value: "custom" },
      ],
      group: "Environment",
    },
    {
      key: "environmentStrength",
      label: "Env Strength",
      type: "float",
      value: 1,
      min: 0,
      max: 2,
      step: 0.01,
      group: "Environment",
    },
    {
      key: "showEnvironmentBackground",
      label: "Show HDRI BG",
      type: "bool",
      value: true,
      group: "Environment",
    },
    {
      key: "environmentBlur",
      label: "BG Blur",
      type: "float",
      value: 0,
      min: 0,
      max: 1,
      step: 0.01,
      group: "Environment",
      description: "Blur amount for HDRI background",
    },
    {
      key: "environmentBackgroundIntensity",
      label: "BG Intensity",
      type: "float",
      value: 1,
      min: 0,
      max: 3,
      step: 0.01,
      group: "Environment",
      description: "Brightness of visible HDRI background",
    },
    {
      key: "background",
      label: "Background",
      type: "color",
      value: "#0b0e10",
      group: "Environment",
    },
    {
      key: "cameraYaw",
      label: "Camera Yaw",
      type: "float",
      value: 0,
      min: -6.283,
      max: 6.283,
      step: 0.01,
      group: "Camera",
    },
    {
      key: "cameraPitch",
      label: "Camera Pitch",
      type: "float",
      value: 0.1,
      min: -1.2,
      max: 1.2,
      step: 0.01,
      group: "Camera",
    },
    {
      key: "cameraDistance",
      label: "Camera Distance",
      type: "float",
      value: 1.0,
      min: 0.4,
      max: 4,
      step: 0.01,
      group: "Camera",
      description: "Distance multiplier relative to fitted model size",
    },
    {
      key: "playAnimation",
      label: "Play Embedded",
      type: "bool",
      value: true,
      group: "Animation",
    },
    {
      key: "autoRotate",
      label: "Auto Rotate",
      type: "bool",
      value: false,
      group: "Animation",
    },
    {
      key: "autoRotateSpeed",
      label: "Rotate Speed",
      type: "float",
      value: 0.6,
      min: -4,
      max: 4,
      step: 0.01,
      group: "Animation",
    },
    {
      key: "modelScale",
      label: "Scale",
      type: "float",
      value: 1,
      min: 0.05,
      max: 4,
      step: 0.01,
      group: "Transform",
    },
    {
      key: "modelOffset",
      label: "Offset",
      type: "vec3",
      value: [0, 0, 0],
      min: -3,
      max: 3,
      step: 0.01,
      group: "Transform",
    },
    {
      key: "modelRotation",
      label: "Rotation",
      type: "vec3",
      value: [0, 0, 0],
      min: -6.283,
      max: 6.283,
      step: 0.01,
      group: "Transform",
    },
  ];
}

export function getDefaultParamsForLayer(
  kind: LayerKind,
  shaderType?: ShaderType,
): ShaderParam[] {
  if (kind === "shader" && shaderType) return getDefaultParams(shaderType);
  if (kind === "model") return getDefaultModelParams();
  return [];
}
